version: '3.8'
services:
  chatbot:
  build: . 
  container_name: teacher_agent
  restart: always 
  environment:
  -GROQ_API_KEY=${GROQ_API_KEY}
  -SERPER_API_KEY=${SERPER_API_KEY}
  volumes: 
   - ./faiss_index:/app/faiss_index